### ISSUE TITLE
safe node run-baby-fleming fails to start any nodes

### ISSUE THREAD

**Issue by happybeing** [maidsafe/safe_network#2070] opened 2023-02-06 17:33 UTC
Can't currently start nodes using `safe node run-baby-fleming` in the latest build (safe_cli  0.69.2, sn_node 0.73.5) because the launch tool is passing an invalid parameter (`--idle-timeout-msec`):

```sh
$ RUST_LOG=sn_node=trace safe node run-baby-fleming
Storing nodes' generated data at /home/mrh/.safe/node/baby-fleming-nodes
Starting a node to join a Safe network...
error: Found argument '--idle-timeout-msec' which wasn't expected, or isn't valid in this context

	If you tried to supply `--idle-timeout-msec` as a value rather than a flag, use `-- --idle-timeout-msec`

USAGE:
    sn_node --verbose

For more information try --help
Error: 
   0: Error launching node
   1: Failed to start '/home/mrh/.safe/node/sn_node' with args '["-vv", "--idle-timeout-msec", "5500", "--skip-auto-port-forwarding", "--local-addr", "127.0.0.1:0", "--first"]'
   2: Node exited early (status: exit status: 2)

Location:
   /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/sn_launch_tool-0.9.4/src/cmd.rs:146
```

**Comment by happybeing** [comment] 2023-02-06 17:35
If the parameter can just be removed I'll try this and be happy to submit a PR.

**Comment by happybeing** [comment] 2023-02-07 15:49
👎 I was looking in the code to see where this is being set and didn't find it yet. I see where the launch tool would do this, but only if it is first passed the same parameter. I don't see what is passing that though 🤷‍♂️

**Comment by b-zee** [comment] 2023-02-16 13:29
I couldn't reproduce this on main with the following:

```
$ cargo run --release --bin=safe -- node install
$ cargo run --release --bin=safe -- node run-baby-fleming
```

Not sure if this was fixed or it's an issue with the binaries that were released.

**Comment by happybeing** [comment] 2023-02-16 17:12
What `sn_node` version is that? I still can't do `safe update` because it gives a 404 error but I did `safe node update` which updated my `sn_node` to v0.75.0 and still get the error.

Wondering if this is a path issue I've tried a few variations (including `safe node bin-version` / `safe node run-baby-fleming` and `/home/mrh/.safe/node/sn_node run-baby-fleming`) but they still give version v0.75.0 and the following error:

```
safe node run-baby-fleming
Storing nodes' generated data at /home/mrh/.safe/node/baby-fleming-nodes
Starting nodes to join the Safe network...
error: Found argument '--skip-auto-port-forwarding' which wasn't expected, or isn't valid in this context

	If you tried to supply `--skip-auto-port-forwarding` as a value rather than a flag, use `-- --skip-auto-port-forwarding`

USAGE:
    sn_node --verbose

For more information try --help
Error: 
   0: Error launching node
   1: Failed to start '/home/mrh/.safe/node/sn_node' with args '["-vv", "--skip-auto-port-forwarding", "--local-addr", "127.0.0.1:0", "--first", "--root-dir", "/home/mrh/.safe/node/baby-fleming-nodes/sn-node-genesis", "--log-dir", "/home/mrh/.safe/node/baby-fleming-nodes/sn-node-genesis"]'
   2: Node exited early (status: exit status: 2)

Location:
   /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/sn_launch_tool-0.12.1/src/cmd.rs:163
```

Is there something else I can try?

**Comment by jacderida** [comment] 2023-02-16 18:00
Sorry, I just noticed my name on this.

Yeah, I should be taking a look at various usability issues starting either today or tomorrow.

The `--skip-auto-port-forwarding` flag has been removed now.

**Comment by jacderida** [comment] 2023-02-16 19:12
It's probably coming from the `node run-baby-fleming` command. I'll look into it in more detail soon, as well as self update.

**Comment by jacderida** [comment] 2023-03-23 14:24
The `node` command has now been removed from `safe` and the recommended way to create local test networks is to use the `testnet` binary.

There haven't been any reported issues with `testnet`.

Going to close this.

**Closed by jacderida** 2023-03-23 14:24 UTC
